/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CapaPresentacion;
import CapaNegocio.DataArticulo;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author fambr
 */
public class FormularioArticulo extends javax.swing.JFrame {

    /**
     * Creates new form FormularioArticulo
     */
    public FormularioArticulo() {
        initComponents();
        this.setSize(800,500);
        ListarArticulos();
        BtnGrabar.setEnabled(false);
        setLocationRelativeTo(null);
    }
    
     public void ListarArticulos(){
        DefaultTableModel tabla = new DefaultTableModel();
        DataArticulo objart = new DataArticulo();
        ArrayList<DataArticulo> lista2 = new ArrayList();
        lista2 = objart.ListaArticulos();
        tabla.addColumn("Codigo");
        tabla.addColumn("Nombre");
        tabla.addColumn("Unidad");
        tabla.addColumn("Precio");
        tabla.addColumn("Stock");
        tabla.addColumn("Marca");
        tabla.setRowCount(lista2.size());
        int i = 0;
        for(DataArticulo x: lista2){
            tabla.setValueAt(x.getArt_cod(), i, 0);
            tabla.setValueAt(x.getArt_nom(), i, 1);
            tabla.setValueAt(x.getArt_uni(), i, 2);
            tabla.setValueAt(x.getArt_pre(), i, 3);
            tabla.setValueAt(x.getArt_stk(), i, 4);
            tabla.setValueAt(x.getArt_marca(), i, 5);
            i++;
        }
        this.jTable1.setModel(tabla);
    }
     
     public void LimpiarCajasTexto(){
         this.TxtFldCodigo.setText("");
         this.TxtFldNombre.setText("");
         this.TxtFldUni.setText("");
         this.TxtFldPrecio.setText("");
         this.TxtFldCantidad.setText("");
         this.TxtFldMarca.setText("");
         
     }
     
     public boolean ValidarVacios(){
         if(this.TxtFldCodigo.getText().equals("")){
             JOptionPane.showMessageDialog(null, "El código está vacío");
             return false;
         }else if (this.TxtFldNombre.getText().equals("")){
             JOptionPane.showMessageDialog(null, "El nombre está vacío");
             return false;
         }else if (this.TxtFldUni.getText().equals("")){
             JOptionPane.showMessageDialog(null, "La unidad de medida está vacía");
             return false;
         }else if (this.TxtFldPrecio.getText().equals("")){
             JOptionPane.showMessageDialog(null, "El precio está vacío");
             return false;
         }else if (this.TxtFldCantidad.getText().equals("")){
             JOptionPane.showMessageDialog(null, "La cantidad está vacía");
             return false;
         }else if (this.TxtFldMarca.getText().equals("")){
             JOptionPane.showMessageDialog(null, "La marca está vacía");
             return false;
         }else{
             return true;
         }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblCodigo = new javax.swing.JLabel();
        LblNombre = new javax.swing.JLabel();
        LblUni = new javax.swing.JLabel();
        LblPrecio = new javax.swing.JLabel();
        LblCantidad = new javax.swing.JLabel();
        LblMarca = new javax.swing.JLabel();
        TxtFldCodigo = new javax.swing.JTextField();
        TxtFldNombre = new javax.swing.JTextField();
        TxtFldUni = new javax.swing.JTextField();
        TxtFldPrecio = new javax.swing.JTextField();
        TxtFldCantidad = new javax.swing.JTextField();
        TxtFldMarca = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BtnNuevo = new javax.swing.JButton();
        BtnGrabar = new javax.swing.JButton();
        BtnModificar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(2000, 600));
        setResizable(false);

        LblCodigo.setText("Código:");
        LblCodigo.setMaximumSize(new java.awt.Dimension(20, 13));
        LblCodigo.setMinimumSize(new java.awt.Dimension(20, 13));
        LblCodigo.setPreferredSize(new java.awt.Dimension(20, 13));

        LblNombre.setText("Nombre:");
        LblNombre.setMaximumSize(new java.awt.Dimension(20, 13));
        LblNombre.setMinimumSize(new java.awt.Dimension(20, 13));
        LblNombre.setPreferredSize(new java.awt.Dimension(20, 13));

        LblUni.setText("Unidad de Medida");
        LblUni.setMaximumSize(new java.awt.Dimension(20, 13));
        LblUni.setMinimumSize(new java.awt.Dimension(20, 13));
        LblUni.setPreferredSize(new java.awt.Dimension(20, 13));

        LblPrecio.setText("Precio");
        LblPrecio.setMaximumSize(new java.awt.Dimension(20, 13));
        LblPrecio.setMinimumSize(new java.awt.Dimension(20, 13));
        LblPrecio.setPreferredSize(new java.awt.Dimension(20, 13));

        LblCantidad.setText("Cantidad");
        LblCantidad.setMaximumSize(new java.awt.Dimension(20, 13));
        LblCantidad.setMinimumSize(new java.awt.Dimension(20, 13));
        LblCantidad.setPreferredSize(new java.awt.Dimension(20, 13));

        LblMarca.setText("Marca");
        LblMarca.setMaximumSize(new java.awt.Dimension(20, 13));
        LblMarca.setMinimumSize(new java.awt.Dimension(20, 13));
        LblMarca.setPreferredSize(new java.awt.Dimension(20, 13));

        TxtFldCodigo.setMaximumSize(new java.awt.Dimension(20, 13));
        TxtFldCodigo.setMinimumSize(new java.awt.Dimension(20, 13));
        TxtFldCodigo.setPreferredSize(new java.awt.Dimension(20, 13));

        TxtFldNombre.setMaximumSize(new java.awt.Dimension(20, 13));
        TxtFldNombre.setMinimumSize(new java.awt.Dimension(20, 13));
        TxtFldNombre.setPreferredSize(new java.awt.Dimension(20, 13));

        TxtFldUni.setMaximumSize(new java.awt.Dimension(20, 13));
        TxtFldUni.setMinimumSize(new java.awt.Dimension(20, 13));
        TxtFldUni.setPreferredSize(new java.awt.Dimension(20, 13));

        TxtFldPrecio.setMaximumSize(new java.awt.Dimension(20, 13));
        TxtFldPrecio.setMinimumSize(new java.awt.Dimension(20, 13));
        TxtFldPrecio.setPreferredSize(new java.awt.Dimension(20, 13));

        TxtFldCantidad.setMaximumSize(new java.awt.Dimension(20, 13));
        TxtFldCantidad.setMinimumSize(new java.awt.Dimension(20, 13));
        TxtFldCantidad.setPreferredSize(new java.awt.Dimension(20, 13));

        TxtFldMarca.setMaximumSize(new java.awt.Dimension(20, 13));
        TxtFldMarca.setMinimumSize(new java.awt.Dimension(20, 13));
        TxtFldMarca.setPreferredSize(new java.awt.Dimension(20, 13));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        BtnNuevo.setLabel("Nuevo");
        BtnNuevo.setMaximumSize(new java.awt.Dimension(80, 25));
        BtnNuevo.setMinimumSize(new java.awt.Dimension(80, 25));
        BtnNuevo.setPreferredSize(new java.awt.Dimension(80, 25));
        BtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNuevoActionPerformed(evt);
            }
        });

        BtnGrabar.setText("Grabar");
        BtnGrabar.setMaximumSize(new java.awt.Dimension(80, 25));
        BtnGrabar.setMinimumSize(new java.awt.Dimension(80, 25));
        BtnGrabar.setPreferredSize(new java.awt.Dimension(80, 25));
        BtnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGrabarActionPerformed(evt);
            }
        });

        BtnModificar.setText("Modificar");
        BtnModificar.setMaximumSize(new java.awt.Dimension(80, 25));
        BtnModificar.setMinimumSize(new java.awt.Dimension(80, 25));
        BtnModificar.setPreferredSize(new java.awt.Dimension(80, 25));
        BtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarActionPerformed(evt);
            }
        });

        BtnEliminar.setLabel("Eliminar");
        BtnEliminar.setMaximumSize(new java.awt.Dimension(80, 25));
        BtnEliminar.setMinimumSize(new java.awt.Dimension(80, 25));
        BtnEliminar.setPreferredSize(new java.awt.Dimension(80, 25));
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        BtnSalir.setLabel("Salir");
        BtnSalir.setMaximumSize(new java.awt.Dimension(80, 25));
        BtnSalir.setMinimumSize(new java.awt.Dimension(80, 25));
        BtnSalir.setPreferredSize(new java.awt.Dimension(80, 25));
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LblUni, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(LblCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(LblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(LblPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(LblCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(LblMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtFldCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(TxtFldNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(TxtFldUni, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(TxtFldPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(TxtFldCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(TxtFldMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LblCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(TxtFldCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtFldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LblUni, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtFldUni, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtFldPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(LblPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtFldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtFldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        LblCodigo.getAccessibleContext().setAccessibleName("LblCodigo");
        LblNombre.getAccessibleContext().setAccessibleName("LblNombre");
        LblUni.getAccessibleContext().setAccessibleName("LblUni");
        LblPrecio.getAccessibleContext().setAccessibleName("LblPrecio");
        LblCantidad.getAccessibleContext().setAccessibleName("LblCantidad");
        LblCantidad.getAccessibleContext().setAccessibleDescription("");
        LblMarca.getAccessibleContext().setAccessibleName("LblMarca");
        TxtFldCodigo.getAccessibleContext().setAccessibleName("TxtFldCodigo");
        TxtFldNombre.getAccessibleContext().setAccessibleName("TxtFldNombre");
        TxtFldUni.getAccessibleContext().setAccessibleName("TxtFldUni");
        TxtFldPrecio.getAccessibleContext().setAccessibleName("TxtFldPrecio");
        TxtFldCantidad.getAccessibleContext().setAccessibleName("TxtFldCantidad");
        TxtFldMarca.getAccessibleContext().setAccessibleName("TxtFldMarca");
        BtnNuevo.getAccessibleContext().setAccessibleName("BtnNuevo");
        BtnGrabar.getAccessibleContext().setAccessibleName("BtnGrabar");
        BtnModificar.getAccessibleContext().setAccessibleName("BtnModificar");
        BtnEliminar.getAccessibleContext().setAccessibleName("BtnEliminar");
        BtnEliminar.getAccessibleContext().setAccessibleDescription("");
        BtnSalir.getAccessibleContext().setAccessibleName("BtnSalir");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        int r = JOptionPane.showConfirmDialog(null, "¿Está Seguro?");
        if (r == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        int rec = this.jTable1.getSelectedRow();
        this.TxtFldCodigo.setText(jTable1.getValueAt(rec, 0).toString());
        this.TxtFldNombre.setText(jTable1.getValueAt(rec, 1).toString());
        this.TxtFldUni.setText(jTable1.getValueAt(rec, 2).toString());
        this.TxtFldPrecio.setText(jTable1.getValueAt(rec, 3).toString());
        this.TxtFldCantidad.setText(jTable1.getValueAt(rec, 4).toString());
        this.TxtFldMarca.setText(jTable1.getValueAt(rec, 5).toString());
    }//GEN-LAST:event_jTable1MousePressed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        int Res = JOptionPane.showConfirmDialog(null, 
                "¿Está Seguro de ELIMINAR el Articulo " + this.TxtFldCodigo.getText());
        if (Res == 0 && ValidarVacios()){
            DataArticulo objart = new DataArticulo();
            objart.setArt_cod(this.TxtFldCodigo.getText());
            JOptionPane.showMessageDialog(null, objart.EliminarArticulo());
            ListarArticulos();
            JOptionPane.showMessageDialog(null, "Articulo Eliminado");
        }
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void BtnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGrabarActionPerformed
        if(ValidarVacios()){
            DataArticulo objart = new DataArticulo();
            objart.setArt_cod(this.TxtFldCodigo.getText());
            objart.setArt_nom(this.TxtFldNombre.getText());
            objart.setArt_uni(this.TxtFldUni.getText());
            objart.setArt_pre(Double.parseDouble(this.TxtFldPrecio.getText()));
            objart.setArt_stk(Integer.parseInt(this.TxtFldCantidad.getText()));
            objart.setArt_marca(this.TxtFldMarca.getText());
            JOptionPane.showMessageDialog(null, objart.GrabarArticulo());
            ListarArticulos();
        }
    }//GEN-LAST:event_BtnGrabarActionPerformed

    private void BtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarActionPerformed
        if(ValidarVacios()){
            DataArticulo objart = new DataArticulo();
            objart.setArt_cod(this.TxtFldCodigo.getText());
            objart.setArt_nom(this.TxtFldNombre.getText());
            objart.setArt_uni(this.TxtFldUni.getText());
            objart.setArt_pre(Double.parseDouble(this.TxtFldPrecio.getText()));
            objart.setArt_stk(Integer.parseInt(this.TxtFldCantidad.getText()));
            objart.setArt_marca(this.TxtFldMarca.getText());
            JOptionPane.showMessageDialog(null, objart.EditarArticulo());
            ListarArticulos();
        }
    }//GEN-LAST:event_BtnModificarActionPerformed

    private void BtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNuevoActionPerformed
        LimpiarCajasTexto();
        BtnGrabar.setEnabled(true);
    }//GEN-LAST:event_BtnNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioArticulo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnGrabar;
    private javax.swing.JButton BtnModificar;
    private javax.swing.JButton BtnNuevo;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JLabel LblCantidad;
    private javax.swing.JLabel LblCodigo;
    private javax.swing.JLabel LblMarca;
    private javax.swing.JLabel LblNombre;
    private javax.swing.JLabel LblPrecio;
    private javax.swing.JLabel LblUni;
    private javax.swing.JTextField TxtFldCantidad;
    private javax.swing.JTextField TxtFldCodigo;
    private javax.swing.JTextField TxtFldMarca;
    private javax.swing.JTextField TxtFldNombre;
    private javax.swing.JTextField TxtFldPrecio;
    private javax.swing.JTextField TxtFldUni;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
